// Regenerates the shared test vector used by both the JS and Rust tests.
// Run from client/:  node scripts/gen-vector.mjs
import { writeFileSync } from 'node:fs';
import {
  cancelHash,
  deriveCancelSecret,
  deriveKey,
  digitsOf,
  messageDigest,
  publicKeyHash,
  sign,
  verifyCost,
} from '../src/wots.js';

const bytes = (n, f) => Buffer.from(Array.from({ length: n }, (_, i) => f(i) & 0xff));
const master = bytes(32, (i) => i);
const index = 7;
const programId = bytes(32, (i) => 0xa0 + i);
const vault = bytes(32, (i) => 7 * i + 5);
const asset = bytes(32, (i) => 11 * i + 2);
const destination = bytes(32, (i) => 3 * i + 1);
const amount = 1234567890123n;

const { pubSeed, secrets } = deriveKey(master, index);
const pubkeyHash = publicKeyHash(pubSeed, secrets);
const next = deriveKey(master, index + 1);
const nextKeyHash = publicKeyHash(next.pubSeed, next.secrets);
const cancelSecret = deriveCancelSecret(master, index);
const commitment = cancelHash(vault, BigInt(index), cancelSecret);
const digest = messageDigest(pubSeed, {
  programId, vault, sequence: BigInt(index), asset, amount, destination, nextKeyHash, cancelHash: commitment,
});
const digits = digitsOf(digest);
const signature = sign(pubSeed, secrets, digits);

const hex = (b) => b.toString('hex');
writeFileSync(
  new URL('../test/vector.json', import.meta.url),
  JSON.stringify(
    {
      master: hex(master), index, programId: hex(programId), vault: hex(vault), asset: hex(asset),
      destination: hex(destination), amount: amount.toString(), pubSeed: hex(pubSeed), pubkeyHash: hex(pubkeyHash),
      nextKeyHash: hex(nextKeyHash), cancelSecret: hex(cancelSecret), cancelHash: hex(commitment),
      digest: hex(digest), digits: hex(digits), hashes: verifyCost(digits), signature: hex(signature),
    },
    null,
    2,
  ) + '\n',
);

const arr = (b) => `[${[...b].join(', ')}]`;
writeFileSync(
  new URL('../../program/tests/vector/mod.rs', import.meta.url),
  `// Generated by client/scripts/gen-vector.mjs. Do not edit.
pub const PROGRAM_ID: [u8; 32] = ${arr(programId)};
pub const VAULT: [u8; 32] = ${arr(vault)};
pub const SEQUENCE: u64 = ${index};
pub const ASSET: [u8; 32] = ${arr(asset)};
pub const DESTINATION: [u8; 32] = ${arr(destination)};
pub const AMOUNT: u64 = ${amount};
pub const PUB_SEED: [u8; 16] = ${arr(pubSeed)};
pub const PUBKEY_HASH: [u8; 32] = ${arr(pubkeyHash)};
pub const NEXT_KEY_HASH: [u8; 32] = ${arr(nextKeyHash)};
pub const CANCEL_SECRET: [u8; 32] = ${arr(cancelSecret)};
pub const CANCEL_HASH: [u8; 32] = ${arr(commitment)};
pub const DIGEST: [u8; 32] = ${arr(digest)};
pub const DIGITS: [u8; ${digits.length}] = ${arr(digits)};
pub const HASHES: u32 = ${verifyCost(digits)};
pub const SIGNATURE: [u8; ${signature.length}] = ${arr(signature)};
`,
);
console.log('wrote test/vector.json and ../program/tests/vector/mod.rs');
